### ISSUE TITLE
opm:Calculation and opm:Assumed as ObjectProperties?

### ISSUE THREAD

**Issue by AnnaWagner** [w3c-lbd-cg/opm#1]
While looking into OPM in detail I noticed that opm:Assumed and opm:Calculation are both defined as ObjectProperties. However, they are listed among the classes of the ontology and in my understanding also should be classes. 
What is correct? Are they classes or properties?

**Comment by MadsHolten** [comment]
They are classes. I will correct it asap. Thanks for the notice!
